services:
  - type: web
    name: accutrack-web
    runtime: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn accutrack_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
