# Generated by Django 5.2.7 on 2026-09-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accutrack_app', '0009_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Startup Guru Business Center', help_text='Company / Center Name (e.g. Startup Guru Business Center)', max_length=255)),
                ('office_address', models.CharField(default='Office No-13, F-14 First Floor', help_text='Office / Floor / Suite (e.g. Office No-13, F-14 First Floor)', max_length=255)),
                ('street_address', models.CharField(default='Al Nahda Street, Al Tawar-1', help_text='Street / Area (e.g. Al Nahda Street, Al Tawar-1)', max_length=255)),
                ('city_country', models.CharField(default='Dubai - UAE', help_text='City & Country (e.g. Dubai - UAE)', max_length=255)),
                ('po_box', models.CharField(default='233642', help_text='P.O. Box Number', max_length=50)),
                ('email', models.EmailField(default='support@accutrack.ae', help_text='Primary support/contact email address', max_length=254)),
                ('phone_number', models.CharField(default='+971 54 333 7493', help_text='Mobile / Primary Phone (displayed on header, contact card, and footer)', max_length=50)),
                ('landline_number', models.CharField(default='+971 4 296 9899', help_text='Landline Number (displayed on footer and contact details)', max_length=50)),
                ('whatsapp_number', models.CharField(default='971543337493', help_text='WhatsApp Number with country code and digits only (e.g. 971543337493)', max_length=50)),
                ('google_maps_embed_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3607.6450180505485!2d55.35089467472997!3d25.282524228240568!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f5c8b80b14ea3%3A0xb88d7b254998748d!2sRoyal%20House%20Building!5e0!3m2!1sen!2sin!4v1733827038163!5m2!1sen!2sin', help_text="Google Maps Embed URL (the 'src' attribute inside Google Maps iframe)")),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
