# Generated by Django 5.2.7 on 2026-09-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accutrack_app', '0010_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='street_address',
            field=models.CharField(default='Al Nahda Street, Al Twar-1', help_text='Street / Area (e.g. Al Nahda Street, Al Twar-1)', max_length=255),
        ),
    ]
